"""add_reason_code_column

Revision ID: 494941ab3c49
Revises: d8303208c05c
Create Date: 2026-05-04 00:22:30.829122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494941ab3c49'
down_revision: Union[str, Sequence[str], None] = 'd8303208c05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_code', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.drop_column('reason_code')

    # ### end Alembic commands ###
