"""add_classified_at_index

Adds an index on ``domain_classifications.classified_at`` so the
``order_by(classified_at.desc())`` in ``GET /api/brands/{slug}/domains``
hits an index instead of a sort. Original autogenerate-suggested filename
mentioned tz-aware columns; that change was reverted before merge — the
schema stays naive UTC throughout. See ``brand_monitor/time.py``.

Revision ID: 9a63bdfbf615
Revises: f6bdef31f92a
Create Date: 2026-05-03 18:55:05.101977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a63bdfbf615'
down_revision: Union[str, Sequence[str], None] = 'f6bdef31f92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_classifications_classified_at'), ['classified_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_classifications_classified_at'))

    # ### end Alembic commands ###
