"""use_text_for_long_string_columns

Revision ID: d8303208c05c
Revises: 9a63bdfbf615
Create Date: 2026-05-03 19:03:51.363514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8303208c05c'
down_revision: Union[str, Sequence[str], None] = '9a63bdfbf615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.alter_column('reasoning',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('serp_results', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('snippet',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serp_results', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)

    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.alter_column('reasoning',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###
