"""init schema

Revision ID: f6bdef31f92a
Revises:
Create Date: 2026-05-03 18:06:40.520670

JSON columns use ``with_variant(JSONB(), "postgresql")`` so Postgres gets
the binary JSONB representation (operators, GIN-index support) while
SQLite stays on plain JSON. Mirrors ``db.models.JsonCol``.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'f6bdef31f92a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _json_col() -> sa.types.TypeEngine:
    """JSON on SQLite, JSONB on Postgres — matches ``models.JsonCol``."""
    return sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=False),
    sa.Column('official_domains', _json_col(), nullable=False),
    sa.Column('known_partners', _json_col(), nullable=False),
    sa.Column('known_competitors', _json_col(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('brand_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'keyword', 'geo', name='uq_brand_kw_geo')
    )
    op.create_table('domain_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stage_used', sa.Integer(), nullable=False),
    sa.Column('signals', _json_col(), nullable=False),
    sa.Column('reasoning', sa.String(length=2048), nullable=False),
    sa.Column('classified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'domain', name='uq_brand_domain_classification')
    )
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_classifications_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_classifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_classifications_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_classifications_subcategory'), ['subcategory'], unique=False)

    op.create_table('serp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_serp', _json_col(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serp_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serp_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_serp_snapshots_geo'), ['geo'], unique=False)
        batch_op.create_index(batch_op.f('ix_serp_snapshots_keyword'), ['keyword'], unique=False)

    op.create_table('serp_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('snippet', sa.String(length=1024), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['domain_classifications.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['serp_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serp_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serp_results_domain'), ['domain'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serp_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serp_results_domain'))

    op.drop_table('serp_results')
    with op.batch_alter_table('serp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serp_snapshots_keyword'))
        batch_op.drop_index(batch_op.f('ix_serp_snapshots_geo'))
        batch_op.drop_index(batch_op.f('ix_serp_snapshots_captured_at'))

    op.drop_table('serp_snapshots')
    with op.batch_alter_table('domain_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_classifications_subcategory'))
        batch_op.drop_index(batch_op.f('ix_domain_classifications_domain'))
        batch_op.drop_index(batch_op.f('ix_domain_classifications_category'))
        batch_op.drop_index(batch_op.f('ix_domain_classifications_brand_id'))

    op.drop_table('domain_classifications')
    op.drop_table('brand_keywords')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))

    op.drop_table('brands')
    # ### end Alembic commands ###
